version: '3'

volumes:
  pg_data_production:
  media:
  static:


services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: ikhit/foodgram_backend:latest
    depends_on:
      - db
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    env_file: .env
    image: ikhit/foodgram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: ikhit/foodgram_gateway:latest
    depends_on:
      - backend
    env_file: .env
    ports:
      - 9500:80
    volumes:
      - static:/static
      - media:/app/media
