COOKING_TIME_MINIMUM = 1
INGREDIENTS_AMOUNT_MIN_VALUE = 1
TAGS_NAME_MAX_LENGTH = 15
TAGS_COLOR_MAX_LENGTH = 16
RECIPE_NAME_MAX_LENGTH = 150
INGREDIENTS_NAME_MAX_LENGTH = 150
INGREDIENTS_MEAS_NAME_MAX_LENGTH = 30