MAX_LENGTH_FOR_NAME = 150
MAX_USER_PASSWORD_LENGTH = 128
COOKING_TIME_MIN = INGREDIENTS_AMOUNT_MIN = 1
COOKING_TIME_MAX = INGREDIENTS_AMOUNT_MAX = 32000
TAGS_NAME_MAX_LENGTH = TAGS_MAX_SLUG_LENGTH = 200
TAGS_COLOR_MAX_LENGTH = 7
RECIPE_NAME_MAX_LENGTH = INGREDIENTS_NAME_MAX_LENGTH = INGREDIENTS_MEAS_NAME_MAX_LENGTH = 200

