# Generated by Django 3.2.16 on 2024-04-06 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ingredients",
            new_name="Ingredient",
        ),
        migrations.RenameModel(
            old_name="Tags",
            new_name="Tag",
        ),
    ]
