# Generated by Django 3.2.16 on 2024-03-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240316_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='recipes',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='recipes_count',
        ),
    ]
