# Generated by Django 3.2.16 on 2024-03-16 15:21

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20240316_1819'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_self_following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('following')), _negated=True), name='user_self_following'),
        ),
    ]
